config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :restaurants do
    collection do
      # get 'restaurants/top', to: 'restaurants#top'
      get :top
    end

    member do
      # get 'restaurants/:id/chef', to: 'restaurants#chef'
      get :chef
    end

    resources :reviews, only: :create
  end

  resources :reviews, only: :destroy

  # # Create
  # get 'restaurants/new', to: 'restaurants#new', as: 'new_restaurant'
  # post 'restaurants',    to: 'restaurants#create'

  # # Read (all)
  # get 'restaurants', to: 'restaurants#index'

  # # Read (one)
  # get 'restaurants/:id', to: 'restaurants#show', as: 'restaurant'

  # # Update (one)
  # get 'restaurants/:id/edit', to: 'restaurants#edit', as: 'edit_restaurant'
  # patch 'restaurants/:id',    to: 'restaurants#update'

  # # Delete (one)
  # delete "restaurants/:id", to: "restaurants#destroy", as: 'delete_restaurant'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :reviews, dependent: :destroy
    
    # def initialize(properties = {})
    #     @name   = properties[:name]
    #     @rating = properties[:rating]
    # end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to restaurants_path
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    before_action :set_restaurant, only: [ :show, :chef, :edit, :update, :destroy ]

    def index
        @restaurants = Restaurant.all
    end

    def top
        # @restaurants = Restaurant.all.select { |restaurant| restaurant.rating == 5 }
        @restaurants = Restaurant.where(rating: 5)
    end

    def show
        @review  = Review.new
        @reviews = @restaurant.reviews
    end

    def chef
        @chef = @restaurant.chef_name
    end

    def new
        @restaurant = Restaurant.new
    end

    def create
        @restaurant = Restaurant.new(restaurant_params)
        redirect_to restaurant_path(@restaurant.id) if @restaurant.save
    end

    def edit; end

    def update
        @restaurant.update(restaurant_params)
        redirect_to restaurant_path(@restaurant.id) if @restaurant.save
    end

    def destroy
        @restaurant.destroy
        redirect_to restaurants_path, status: :see_other
    end

    private

    def set_restaurant
        @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
        params.require(:restaurant).permit(:name, :address, :rating)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def create
        @review = Review.new(review_params)
        @restaurant = Restaurant.find(params[:restaurant_id])
        @review.restaurant = @restaurant

        if @review.save 
            redirect_to restaurant_path(@restaurant)
        else
            render :show, status: :unprocessable_entity
        end
    end

    def destroy
        @review = Review.find(params[:id])
        @review.destroy
        redirect_to restaurant_path(@review.restaurant)
        #status: :see_other
    end

    private

    def review_params
        params.require(:review).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantGuide</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container mt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with model: @restaurant do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :address %>
    <%= f.text_field :address %>
    <%= f.label :rating %>
    <%= f.number_field :rating %>
    <%= f.submit %>
<% end %>

<%= link_to "Back", :back %>

app/views/restaurants/_list.html.erb
<ul>
    <% @restaurants.each do |restaurant| %>
        <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
    <% end %>
</ul>

app/views/restaurants/chef.html.erb
<h1>Details on <%= @restaurant.name %></h1>
<h3>The chef is <%= @chef %></h3>

<%= link_to "Back", :back %>

app/views/restaurants/edit.html.erb
<h1>Edit <%= @restaurant.name %></h1>
<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>All Restaurants 🍝</h1>
<%= render 'list' %>

<%= link_to "Add a restaurant", new_restaurant_path %>
<br>
<%= link_to "Top restaurants", top_restaurants_path %>

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1>Details on <%= @restaurant.name %></h1>
<h3><%= "⭐ " * @restaurant.rating %></h3>
<h4>Address: <%= @restaurant.address %></h4>

<%= link_to "Edit restaurant", edit_restaurant_path(@restaurant) %> |
<%= link_to "Delete restaurant", restaurant_path(@restaurant), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %> |
<%= link_to "Discover chef", chef_restaurant_path(@restaurant) %> |
<br>

<h3 class="mt-4">Reviews</h3>
<% @reviews.each do |review| %>
    <p><%= review.content %></p>
    <%= link_to "x", review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
<% end %>

<h4>Leave a review</h4>
<%= simple_form_for [ @restaurant, @review ] do |f| %>
    <%= f.input :content %>
    <%= f.submit %>
<% end %>


<%= link_to "To home", restaurants_path %>

app/views/restaurants/top.html.erb
<h1>Only the best!</h1>
<%= render 'list' %>

<%= link_to "To home", restaurants_path %>